# Generated by Django 4.0.1 on 2022-01-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of problem', max_length=100)),
                ('description', models.TextField(help_text='Description of problem.')),
                ('screenshot', models.FileField(blank=True, upload_to='worksheets')),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High'), ('VERY HIGH', 'Very High')], max_length=20)),
                ('created_by', models.CharField(default='USER', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED UP', 'Picked Up'), ('EXTENDED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
