# Generated by Django 4.0.1 on 2022-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='importance',
            field=models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High'), ('VERY HIGH', 'Very High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.FileField(blank=True, upload_to='worksheets'),
        ),
    ]
